language: android
android:
  components:
    - build-tools-28.0.3
    - build-tools-26.0.2
    - android-28
    - android-26
    - add-on
    - extra
    - platform-tools
    - tools
    - extra-google-googleplayservices
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-28
    - sys-img-armeabi-v7a-android-26

env:
  global:
    # Add this
    - MALLOC_ARENA_MAX=2

sudo: required

before_install:
  - yes | sdkmanager "platforms;android-26"
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "platforms;android-30"
  - chmod +x gradlew

before_script:
  # Create and start emulator
  - android list sdk --extended --all
  - echo "y" | android update sdk -a --filter sys-img-armeabi-v7a-android-26
  - echo "n" | android create avd --name myandroid26 -t "android-26"
  - emulator -avd test -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script: ./gradlew :app:build

deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: app/build/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    tags: true